### ISSUE TITLE
Question on Image Queries in Decoder Layer

### ISSUE THREAD

**Issue by misoyuri** [iSEE-Laboratory/Frozen-DETR#1]
Hi,

First of all, I would like to commend you on your intuitive research work.
I have been reviewing your code and have a question regarding specific implementation:

#### Handling Image Queries in the Decoder Layer
According to Figure 2 and Section 3.2 of your paper, the image queries are supposed to be discarded after passing through the self-attention module. 
However, in the code implementation, I noticed that the image queries are decoupled after the decoder layer’s forward pass, rather than being discarded as described.

Relevant Code Link: [Deformable Transformer Decoder Layer](https://github.com/iSEE-Laboratory/Frozen-DETR/blob/main/DINO-coco/models/dino/deformable_transformer.py#L326)

- Question:
  - Could you clarify the discrepancy between the paper’s description and the code implementation regarding the handling of image queries?

**Comment by fushh** [comment]
Thanks for your interest.

For simplicity, our implementation is actually decoupling the image queries after the decoder layer’s forward pass but **before calculating the loss**. In Cross-Attention and FFN, **there is no interaction between queries**, thus it is the same  to discard image queries  after passing through the self-attention module or after the decoder layer’s forward pass.

I hope my answer is helpful to you. Best wishes!
