### ISSUE TITLE
Missing Scripts Folder in DINO-coco Codebase

### ISSUE THREAD

**Issue by liukqchoco** [iSEE-Laboratory/Frozen-DETR#2]
Hello, first and foremost, thank you for your excellent work, which has provided us with significant inspiration. As we attempted to further reproduce your work through the code, we noticed that the `scripts` folder and its associated scripts mentioned in the README are missing from the DINO-coco directory. It’s possible this was an oversight amidst your busy schedule. If it’s convenient, we would be extremely grateful if you could provide these files, as having the complete code would be invaluable to us. Thank you very much for your time and consideration!

**Comment by fushh** [comment]
We are pretty sorry for upload mistakes. The files are now uploaded. Thanks for your interest and feedback.
